---
- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Add Grafana APT key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_os_family == 'Debian' and "monitoring" in group_names

- name: Add Grafana APT repo
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  when: ansible_os_family == 'Debian' and "monitoring" in group_names

- name: Install agent packages on all nodes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ monitoring_agent_packages }}"
  when: ansible_os_family == 'Debian'

- name: Install monitoring server packages (Prometheus, Alertmanager, Grafana)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ monitoring_server_packages }}"
  when: ansible_os_family == 'Debian' and "monitoring" in group_names

- name: Ensure services are enabled and started
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - prometheus
    - alertmanager
    - grafana-server
  when: "monitoring" in group_names 