---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-debian11-ansible:latest
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  log: true
  playbooks:
    converge: playbook.yml

verifier:
  name: ansible
  verify_playbook: verify.yml 