# Azure dynamic inventory using azure_rm plugin
---
plugin: azure_rm
# Auth via OIDC login effectué par l'action azure/login
auth_source: auto
use_cli_credentials: true

# Inclure uniquement les VMs taguées environment=dev
filters:
  tags:
    environment: "dev"

# Variable d'hôte principale
compose:
  ansible_host: private_ip_address

# Groupes basés sur les tags
keyed_groups:
  - key: tags.role
    prefix: ""
  - key: tags.environment
    prefix: "env"

# Groupes pratiques pour les playbooks
conditional_groups:
  app: "tags.role is defined and tags.role == 'app'"
  db: "tags.role is defined and tags.role == 'db'"
  monitoring: "tags.role is defined and tags.role == 'monitoring'" 