---
- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: reload systemd
  ansible.builtin.command: systemctl daemon-reload
  become: true
  listen: restart prometheus 