name: cd-dev

env:
  INVENTORY: ansible/inventory/azure_rm.yml
  PLAYBOOK: ansible/site.yml
  AZURE_RG: tpcicd-rg
  AZURE_MON_VM: tpcicd-mon-vm

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible & Collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible "ansible[azure]"
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run Ansible Playbook (dev)
        run: |
          ansible-playbook -i ${{ env.INVENTORY }} ${{ env.PLAYBOOK }} --extra-vars "target_env=dev"

      - name: Health check Prometheus
        run: |
          MON_IP=$(az vm show -g "${{ env.AZURE_RG }}" -n "${{ env.AZURE_MON_VM }}" --show-details --query publicIps -o tsv || echo "")
          if [ -n "$MON_IP" ]; then
            echo "Waiting Prometheus at $MON_IP:9090"
            curl --retry 10 --retry-delay 5 --retry-connrefused http://$MON_IP:9090/-/healthy
          else
            echo "Monitoring VM IP not found, skipping check"
          fi 