name: cd-prod

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible & Collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible "ansible[azure]"
          ansible-galaxy collection install -r ansible/requirements.yml

      - name: Export Azure subscription ID for Ansible inventory
        run: echo "AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)" >> $GITHUB_ENV

      - name: Run Ansible Playbook (prod)
        run: |
          ansible-playbook -i ansible/inventory/azure_rm.yml ansible/site.yml --extra-vars "target_env=prod" 